from django.db import transaction
from django.core.exceptions import ObjectDoesNotExist

from apps.account.domain.aggregates.user_account import UserAccount
from apps.account.domain.value_objects.email import Email
from apps.account.domain.value_objects.nickname import NickName
from apps.account.domain.value_objects.socialLink import SocialLink
from apps.account.domain.repositories import UserAccountRepository
from apps.account.infrastructure.models import Users, UserSocialAccounts 

class DjangoUserAccountRepository(UserAccountRepository):

    def generate_next_id(self):
        raise NotImplementedError("ID is auto-generated by the database.")
    
    def _to_domain_object(self, user_model):
        social_links_vo_list = []
        for link_model in user_model.social_accounts.all():

            social_links_vo_list.append(
                SocialLink(provider_name=link_model.provider, social_id=link_model.provider_account_id)
            )
        
        return UserAccount(
            account_id=user_model.id,
            email=Email(user_model.email_address),
            nickname=NickName(user_model.nickname),
            social_links=social_links_vo_list,
            created_at=user_model.created_at,
            last_login_at=user_model.last_login_at
        )

    @transaction.atomic
    def save(self, user_account):
        is_new = not Users.objects.filter(id=user_account.account_id).exists() \
             if user_account.account_id and \
                user_account.account_id > 0 else True
        
        if is_new:
            user_model = Users()
            if user_account.account_id and user_account.account_id > 0:
                user_model.id = user_account.account_id
        else:
            user_model = Users.objects.get(id=user_account.account_id)
        
        user_model.email_address = user_account.email.address
        user_model.nickname = user_account.nickname.name
        user_model.last_login_at = user_account.last_login_at

        if is_new and user_account.created_at:
            if not Users.objects.filter(id=user_model.id).exists():
                pass
            else:
                if hasattr(user_model, 'created_at') and not user_model.created_at:
                    user_model.created_at = user_account.created_at

        user_model.save()

        UserSocialAccounts.objects.filter(user=user_model).delete()
        for social_link_vo in user_account.social_links:
            UserSocialAccounts.objects.create(
                user=user_model,
                provider=social_link_vo.provider_name,
                provider_account_id = social_link_vo.social_id
            )
        
        saved_user_model = Users.objects.get(id=user_model.id)
        return self._to_domain_object(saved_user_model)
    
    @transaction.atomic
    def delete(self, account_id):
        try:
            user_model = Users.objects.get(id=account_id)
            user_model.delete()
        except Users.DoesNotExist:
            pass
    
    def find_by_id(self, account_id):
        try:
            user_model = Users.objects.get(id=account_id)
            return self._to_domain_object(user_model)
        except Users.DoesNotExist:
            return None
    
    def find_by_email(self, email):
        try:
            user_model = Users.objects(email_address=email.address)
            return self._to_domain_object(user_model)
        except Users.DoesNotExist:
            return None
    
    def find_by_nickname(self, nickname):
        try:
            user_model = Users.objects.get(nickname=nickname.name)
            return self._to_domain_object(user_model)
        except Users.DoesNotExist:
            return None

    def find_by_social_link(self, social_link):
        try:
            link_model = UserSocialAccounts.objects.get(
                provider=social_link.provider_name,
                provider_account_id=social_link.social_id
            )
            return self._to_domain_object(link_model.user)
        except UserSocialAccounts.DoesNotExist:
            return None

