# Generated by Django 4.2.16 on 2025-05-23 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserSocialAccounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google')], max_length=50)),
                ('provider_account_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_account', to='account.users')),
            ],
            options={
                'verbose_name': '사용자 소셜 계정',
                'verbose_name_plural': '사용자 소셜 계정 목록',
                'db_table': 'user_social_account',
                'unique_together': {('user', 'provider'), ('provider', 'provider_account_id')},
            },
        ),
    ]
